config/routes.rb
Rails.application.routes.draw do
  resources :countries do
    resources :dishes, shallow: true
  end
  
  get '/auth/:provider/callback', to: 'sessions#create'

  get '/auth/:provider', to: lambda{|env| [404, {}, ["Not Found"]]}, as: 'auth'

  get '/logout', to: 'sessions#destroy', as: 'logout'
  
  #...go
  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => "countries#index"
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/country.rb
class Country < ApplicationRecord
  validates :name, presence: true
  validates_length_of :name, :within => 1..40
  has_many :dishes
end

app/models/dish.rb
class Dish < ApplicationRecord
  validates :title, presence: true
  validates_length_of :title, :within => 1..25
  validates :recipe, presence: true
  belongs_to :country
  
  has_attached_file :image, styles: {large: "600x600>", medium: "300x300>", thumb: "100x100#"}, default_url: "/images/:style/missing.png"
  validates_attachment :image,
  content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }
end

app/models/user.rb
class User < ApplicationRecord

  def self.from_omniauth(hash)
    user = User.find_or_create_by(uid: hash['uid'], provider: hash['provider'])
    user.name = hash['info']['name']
    user.nickname = hash['info']['nickname']
    user.image = hash['info']['image']
    user.location = hash['info']['location']
    user.save!
    user
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  private

  def current_user
    @current_user ||= User.find_by(id: session[:id])
  end

  helper_method :current_user
  
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_action :set_country, only: [:show, :edit, :update, :destroy]

  # GET /countries
  # GET /countries.json
  def index
    @countries = Country.all
  end

  # GET /countries/1
  # GET /countries/1.json
  def show
  end

  # GET /countries/new
  def new
    @country = Country.new
  end

  # GET /countries/1/edit
  def edit
  end

  # POST /countries
  # POST /countries.json
  def create
    @country = Country.new(country_params)

    respond_to do |format|
      if @country.save
        format.html { redirect_to @country, notice: 'Country was successfully created.' }
        format.json { render :show, status: :created, location: @country }
      else
        format.html { render :new }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /countries/1
  # PATCH/PUT /countries/1.json
  def update
    respond_to do |format|
      if @country.update(country_params)
        format.html { redirect_to @country, notice: 'Country was successfully updated.' }
        format.json { render :show, status: :ok, location: @country }
      else
        format.html { render :edit }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /countries/1
  # DELETE /countries/1.json
  def destroy
    @country.destroy
    respond_to do |format|
      format.html { redirect_to countries_path, notice: 'Country was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_country
      @country = Country.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def country_params
      params.require(:country).permit(:name)
    end
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_action :set_dish, only: [:show, :edit, :update, :destroy]
  before_action :set_country, only: [:index, :new, :create]

  # GET /dishes
  # GET /dishes.json
  def index
    @dishes = Dish.all
  end

  # GET /dishes/1
  # GET /dishes/1.json
  def show
  end

  # GET countries/:country_id/dishes/new
  def new
    @dish = Dish.new
  end

  # GET /dishes/1/edit
  def edit
    @country = Dish.find(params[:id]).country_id
  end

  # POST countries/:country_id/dishes
  # POST countries/:country_id/dishes.json
  def create
    @dish = Dish.new(dish_params)
    @dish.country_id = @country.id

    respond_to do |format|
      if @dish.save
        format.html { redirect_to @dish, notice: 'Dish was successfully created.' }
        format.json { render :show, status: :created, location: @dish }
      else
        format.html { render :new }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dishes/1
  # PATCH/PUT /dishes/1.json
  def update
    respond_to do |format|
      if @dish.update(dish_params)
        format.html { redirect_to @dish, notice: 'Dish was successfully updated.' }
        format.json { render :show, status: :ok, location: @dish }
      else
        format.html { render :edit }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dishes/1
  # DELETE /dishes/1.json
  def destroy
    @country = @dish.country_id
    @dish.destroy
    respond_to do |format|
      format.html { redirect_to country_dishes_url(@country), notice: 'Dish was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dish
      @dish = Dish.find(params[:id])
    end
    def set_country
      @country = Country.find(params[:country_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dish_params
      params.require(:dish).permit(:title, :recipe, :image)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    # render text: request.env['omniauth.auth'].to_yaml
    @user = User.from_omniauth(request.env['omniauth.auth'])
    session[:id] = @user.id
    redirect_to countries_path
  end
  
  def auth_hash
    request.env['omniauth.auth']
  end

  def destroy
    reset_session
    redirect_to countries_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/countries/_form.html.haml
= form_for(country) do |f|
  - if country.errors.any?
    #error_explanation
      %h2
        = pluralize(country.errors.count, "error")
        prohibited this country from being saved:
      %ul
        - country.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit

app/views/countries/edit.html.haml
%h1 Editing Country
= render 'form', country: @country
= link_to 'Show', @country
|
= link_to 'Back', countries_path

app/views/countries/index.html.haml
%p#notice= notice

%h1 An Arabic Cookbook

%p Pick a country below to see some recipes from around the world!

%table
  %thead
    %tr
      %th
      %th
      %th
      %th

  %tbody
    - @countries.each do |country|
      %tr
        %td= country.name
        %td= link_to 'Show', country
        %td= link_to 'Edit', edit_country_path(country)
        %td= link_to 'Destroy', country, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'Add New Country', new_country_path

app/views/countries/new.html.haml
%h1 New Country
= render 'form', country: @country
= link_to 'Back', countries_path

app/views/countries/show.html.haml
%p#notice= notice

%h1
  = @country.name
  
%table
  %thead
    %tr
      %th
      %th
      %th
      %th
      %th
      
  %tbody    
    - @country.dishes.each do |dish|
      %tr
      %td= image_tag(dish.image.url(:thumb))
      %td= dish.title 
      %td= link_to 'Show', dish
      %td= link_to 'Edit', edit_dish_path(dish)
      %td= link_to 'Destroy', dish, :method => :delete, :data => { :confirm => 'Are you sure?' }
%br/
%p 
  = link_to 'Add New Dish', new_country_dish_path(@country)
  |
  = link_to 'Back to All Countries', countries_path

app/views/dishes/_form.html.haml
= form_for @dish , {url: url, html: { multipart: true }} do |f|
  - if @dish.errors.any?
    #error_explanation
      %h2
        = pluralize(@dish.errors.count, "error")
        prohibited this dish from being saved:
      %ul
        - @dish.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :recipe
    = f.text_area :recipe, rows: 10, cols: 60 
  .field
    - if @dish.image.file?
      %h3 Current Image
      .image
        = image_tag @dish.image.url(:thumb)
    = f.label :image
    = f.file_field :image
  .actions
    = f.submit  'Save'

app/views/dishes/edit.html.haml
%h1 Editing Dish
= render 'form', url: dish_path
= link_to 'View Current Dish', @dish
|
= link_to 'Back to All Dishes', country_path(@dish.country)

app/views/dishes/index.html.haml
%p#notice= notice

%h1
  = @country.name
  
%ul
  - @country.dishes.each do |dish|
    %li
      = dish.title 
      = link_to 'Show', dish
      = link_to 'Edit', edit_dish_path(dish)
      = link_to 'Destroy', dish, :method => :delete, :data => { :confirm => 'Are you sure?' }
%br/
%p 
  = link_to 'New Dish', new_country_dish_path(@country)
  |
  = link_to 'Back', countries_path

app/views/dishes/new.html.haml
%h1
   New Dish in
   = @country.name
= render 'form', url: new_country_dish_path(@country)
|
= link_to 'Back', country_path(@country)

app/views/dishes/show.html.haml
%p#notice= notice
%p
  = @dish.title

-# THE NEXT FEW LINES CAN BE ADDED AT A LATER TIME  
-#%p
  -#submitted by:
  -#= @user.nickname
  -#under
  -#= @dish.country.name
  
%p
  - if @dish.image.file?
    .image
    = image_tag @dish.image.url(:medium)
%p
  = @dish.recipe
%p 
  = link_to 'Edit this Dish', edit_dish_path(@dish) 
  |
  = link_to 'Back to Dishes', country_path(@dish.country)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Arabic Dishes
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %header#header
      %p
        - if current_user
          Welcome,
          = current_user.name
          = link_to 'Log Out', logout_path
        - else
          = link_to 'Log in with Twitter', auth_path('twitter')
    = yield